---
abstract: 'Plack handler for the STOMP protocol'
author:
  - 'Gianni Ceccarelli <gianni.ceccarelli@net-a-porter.com>'
build_requires:
  Moose::Role: 0
  Net::Stomp::Frame: 0
  Test::More: 0
  Test::Routine: 0
  Test::Routine::Util: 0
  parent: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Plack-Handler-Stomp
no_index:
  directory:
    - t/lib
requires:
  HTTP::Request: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0
  Net::Stomp: 0
  Try::Tiny: 0
  namespace::autoclean: 0
resources:
  repository: git://github.com/dakkar/plack-handler-stomp.git
version: 0.001_01
